// ===========================================
// RenderHistoryHtml.mjs — static bilingual history page
// ===========================================

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BuildDemoHistory } from './BuildLocalizedHistory.mjs';

/**
 * Writes dist/history.html + dist/history.json from merged releases.
 * The page switches language client-side using pre-translated payloads —
 * it never imports LocalDemoTranslationProvider directly.
 *
 * @param {object} _options
 * @param {object[]} _options.releases
 * @param {string} _options.outDir
 * @param {string[]} [_options.lids]
 * @returns {{ htmlPath: string, jsonPath: string }}
 */
export function RenderHistoryHtml(_options) {
	let lids = _options.lids?.length ? _options.lids : ['en-US', 'de-DE'];
	let payloads = {};
	for (let lid of lids) {
		payloads[lid] = BuildDemoHistory(_options.releases, lid);
	}

	mkdirSync(_options.outDir, { recursive: true });
	let jsonPath = join(_options.outDir, 'history.json');
	let htmlPath = join(_options.outDir, 'history.html');
	writeFileSync(jsonPath, `${JSON.stringify(payloads, null, '\t')}\n`, 'utf8');
	writeFileSync(htmlPath, _HtmlDocument(payloads), 'utf8');
	return { htmlPath, jsonPath };
}

/**
 * @param {Record<string, object>} _payloads
 */
function _HtmlDocument(_payloads) {
	let embedded = JSON.stringify(_payloads).replace(/</g, '\\u003c');
	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Release history — µGulp blog demo</title>
<style>
:root {
	--bg: #101214;
	--panel: #1a1d22;
	--text: #e8ecf1;
	--dim: #8b939e;
	--cyan: #00e5ff;
	--border: #2a2e34;
	--font: "Segoe UI", system-ui, sans-serif;
}
* { box-sizing: border-box; }
body {
	margin: 0;
	min-height: 100vh;
	font-family: var(--font);
	background: radial-gradient(circle at 20% 0%, #1a2430, var(--bg) 55%);
	color: var(--text);
}
main {
	max-width: 720px;
	margin: 0 auto;
	padding: 2.5rem 1.25rem 4rem;
}
header h1 {
	margin: 0 0 .35rem;
	font-size: 1.65rem;
	letter-spacing: .02em;
}
header p {
	margin: 0 0 1.25rem;
	color: var(--dim);
	line-height: 1.45;
}
.lang {
	display: flex;
	gap: .5rem;
	margin-bottom: 1.5rem;
}
.lang button {
	appearance: none;
	border: 1px solid var(--border);
	background: transparent;
	color: var(--text);
	padding: .4rem .85rem;
	border-radius: 4px;
	cursor: pointer;
	font: inherit;
}
.lang button[aria-pressed="true"] {
	border-color: var(--cyan);
	color: var(--cyan);
}
.release {
	background: var(--panel);
	border: 1px solid var(--border);
	border-radius: 8px;
	padding: 1rem 1.1rem;
	margin-bottom: .75rem;
}
.release h2 {
	margin: 0 0 .6rem;
	font-size: 1rem;
	font-weight: 600;
	color: var(--cyan);
}
.release ul {
	margin: 0;
	padding-left: 1.1rem;
}
.release li {
	margin: .25rem 0;
	line-height: 1.4;
}
footer {
	margin-top: 2rem;
	color: var(--dim);
	font-size: .85rem;
}
</style>
</head>
<body>
<main>
<header>
	<h1 id="title">Release history</h1>
	<p>Blog demo: merged <code>RELEASES.json</code> through an opaque translation adapter (local provider today, i18xe-sync / i18x later).</p>
</header>
<nav class="lang" aria-label="Language">
	<button type="button" data-lid="en-US" aria-pressed="true">English</button>
	<button type="button" data-lid="de-DE" aria-pressed="false">Deutsch</button>
</nav>
<section id="history" aria-live="polite"></section>
<footer>Generated by the release-management example. UI uses pre-built payloads only — not the translation provider.</footer>
</main>
<script>
const PAYLOADS = ${embedded};
function render(lid) {
	const data = PAYLOADS[lid] || PAYLOADS['en-US'];
	document.getElementById('title').textContent = data.title;
	document.querySelectorAll('.lang button').forEach((btn) => {
		btn.setAttribute('aria-pressed', btn.dataset.lid === lid ? 'true' : 'false');
	});
	const root = document.getElementById('history');
	root.replaceChildren();
	for (const item of data.items) {
		const article = document.createElement('article');
		article.className = 'release';
		const h2 = document.createElement('h2');
		h2.textContent = item.summary;
		article.appendChild(h2);
		const ul = document.createElement('ul');
		for (const line of item.lines) {
			const li = document.createElement('li');
			li.textContent = line;
			ul.appendChild(li);
		}
		article.appendChild(ul);
		root.appendChild(article);
	}
}
document.querySelectorAll('.lang button').forEach((btn) => {
	btn.addEventListener('click', () => render(btn.dataset.lid));
});
render('en-US');
</script>
</body>
</html>
`;
}
